### ISSUE TITLE
Public Testnet Validator

### ISSUE THREAD

**Issue by dpdanpittman** [settlus/chain#187]
Hi, 

Which channels are you guys using for public testnet validator comms?  We just launched a node on the network and want to make sure we are staying up to date. I also noticed that the voting period is 10 minutes for creating a validator by governance. When is a good time to submit the proposal?

https://testnet.settlus.network/proposal/11

**Comment by uhyunpark** [comment]
Hello @dpdanpittman , thank you for submitting a proposal. We are planning to expand the validator groups within a month. Stay tuned to our social media channels.

**Comment by dpdanpittman** [comment]
That's great!  I have 4 years of Cosmos experience in development and infrastructure management.  Will be happy to support the project.
