### ISSUE TITLE
Something wrong with the commands? It's not working.

### ISSUE THREAD

**Issue by manish8227** [settlus/chain#188]
![Screenshot 2024-06-21 170629](https://github.com/settlus/chain/assets/50174038/0cebbc44-7c9a-4557-98b8-f48efd953629)
it should have been like this, no? : 

curl https://get.ignite.com/cli | bash
brew install golangci-lint

**Comment by uhyunpark** [comment]
It works fine(mac terminal). What environment did you run the command in?
